# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'new_transmision_tramo_linea.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_NewBook(object):
    def setupUi(self, NewBook):
        if not NewBook.objectName():
            NewBook.setObjectName(u"NewBook")
        NewBook.resize(1163, 652)
        NewBook.setMinimumSize(QSize(1163, 535))
        NewBook.setMaximumSize(QSize(1163, 652))
        NewBook.setStyleSheet(u"QPushButton\n"
"{	\n"
"	height: 2em;\n"
" 	border-style: solid;\n"
"	border-width: 2px;\n"
" 	border-color: grey;\n"
"	font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	background-color:grey;\n"
"	color:white;\n"
"}")
        self.label = QLabel(NewBook)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 1131, 41))
        font = QFont()
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet(u"background-color: red;")
        self.label.setFrameShape(QFrame.Box)
        self.label_autoriza = QLabel(NewBook)
        self.label_autoriza.setObjectName(u"label_autoriza")
        self.label_autoriza.setGeometry(QRect(20, 50, 101, 25))
        self.inputCodigo = QLineEdit(NewBook)
        self.inputCodigo.setObjectName(u"inputCodigo")
        self.inputCodigo.setGeometry(QRect(20, 75, 111, 31))
        font1 = QFont()
        font1.setPointSize(12)
        self.inputCodigo.setFont(font1)
        self.inputCodigo.setMaxLength(15)
        self.inputCentral = QLineEdit(NewBook)
        self.inputCentral.setObjectName(u"inputCentral")
        self.inputCentral.setGeometry(QRect(140, 75, 221, 31))
        self.inputCentral.setFont(font1)
        self.addButton = QPushButton(NewBook)
        self.addButton.setObjectName(u"addButton")
        self.addButton.setGeometry(QRect(300, 590, 291, 41))
        font2 = QFont()
        font2.setPointSize(14)
        font2.setBold(True)
        font2.setWeight(75)
        self.addButton.setFont(font2)
        self.addButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.addButton.setStyleSheet(u"QPushButton\n"
"{	\n"
"	height: 2em;\n"
" 	border-style: solid;\n"
"	border-width: 2px;\n"
" 	border-color: #0069c0;\n"
"	font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	background-color:#0069c0;\n"
"	color:white;\n"
"}")
        icon = QIcon()
        icon.addFile(u"./assets/icons/add-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.addButton.setIcon(icon)
        self.addButton.setIconSize(QSize(30, 30))
        self.addButton.setAutoDefault(True)
        self.addButton.setFlat(True)
        self.cancelButton = QPushButton(NewBook)
        self.cancelButton.setObjectName(u"cancelButton")
        self.cancelButton.setGeometry(QRect(600, 590, 271, 41))
        self.cancelButton.setFont(font2)
        self.cancelButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.cancelButton.setStyleSheet(u"QPushButton\n"
"{	\n"
"	height: 2em;\n"
" 	border-style: solid;\n"
"	border-width: 2px;\n"
" 	border-color: grey;\n"
"	font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	background-color:grey;\n"
"	color:white;\n"
"}")
        icon1 = QIcon()
        icon1.addFile(u"./assets/icons/cancel-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.cancelButton.setIcon(icon1)
        self.cancelButton.setIconSize(QSize(30, 30))
        self.cancelButton.setAutoDefault(True)
        self.cancelButton.setFlat(True)
        self.label_aquienVisita = QLabel(NewBook)
        self.label_aquienVisita.setObjectName(u"label_aquienVisita")
        self.label_aquienVisita.setGeometry(QRect(140, 50, 191, 25))
        self.label_area = QLabel(NewBook)
        self.label_area.setObjectName(u"label_area")
        self.label_area.setGeometry(QRect(730, 50, 191, 25))
        self.label_horaSalida = QLabel(NewBook)
        self.label_horaSalida.setObjectName(u"label_horaSalida")
        self.label_horaSalida.setGeometry(QRect(530, 290, 81, 25))
        self.label_motivoVisita = QLabel(NewBook)
        self.label_motivoVisita.setObjectName(u"label_motivoVisita")
        self.label_motivoVisita.setGeometry(QRect(660, 290, 111, 25))
        self.label_nota_obligatoria = QLabel(NewBook)
        self.label_nota_obligatoria.setObjectName(u"label_nota_obligatoria")
        self.label_nota_obligatoria.setGeometry(QRect(20, 580, 281, 21))
        self.ast_aquienvisita = QLabel(NewBook)
        self.ast_aquienvisita.setObjectName(u"ast_aquienvisita")
        self.ast_aquienvisita.setGeometry(QRect(70, 50, 21, 25))
        self.label_advertencia_dni = QLabel(NewBook)
        self.label_advertencia_dni.setObjectName(u"label_advertencia_dni")
        self.label_advertencia_dni.setGeometry(QRect(20, 580, 251, 21))
        self.label_area_2 = QLabel(NewBook)
        self.label_area_2.setObjectName(u"label_area_2")
        self.label_area_2.setGeometry(QRect(370, 50, 141, 25))
        self.cbEstado = QComboBox(NewBook)
        self.cbEstado.setObjectName(u"cbEstado")
        self.cbEstado.setGeometry(QRect(530, 315, 121, 31))
        self.cbEstado.setFont(font1)
        self.cbEstado.setEditable(False)
        self.inputFecha = QDateEdit(NewBook)
        self.inputFecha.setObjectName(u"inputFecha")
        self.inputFecha.setGeometry(QRect(660, 315, 111, 31))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(False)
        font3.setWeight(50)
        self.inputFecha.setFont(font3)
        self.cbTipo = QComboBox(NewBook)
        self.cbTipo.setObjectName(u"cbTipo")
        self.cbTipo.setGeometry(QRect(530, 75, 191, 31))
        self.cbTipo.setFont(font1)
        self.cbTipo.setEditable(False)
        self.label_area_3 = QLabel(NewBook)
        self.label_area_3.setObjectName(u"label_area_3")
        self.label_area_3.setGeometry(QRect(530, 50, 141, 25))
        self.label_autoriza_4 = QLabel(NewBook)
        self.label_autoriza_4.setObjectName(u"label_autoriza_4")
        self.label_autoriza_4.setGeometry(QRect(220, 110, 151, 25))
        self.inputLogitud = QLineEdit(NewBook)
        self.inputLogitud.setObjectName(u"inputLogitud")
        self.inputLogitud.setGeometry(QRect(730, 135, 201, 31))
        self.inputLogitud.setFont(font1)
        self.inputLogitud.setMaxLength(12)
        self.label_autoriza_5 = QLabel(NewBook)
        self.label_autoriza_5.setObjectName(u"label_autoriza_5")
        self.label_autoriza_5.setGeometry(QRect(940, 50, 151, 25))
        self.label_autoriza_6 = QLabel(NewBook)
        self.label_autoriza_6.setObjectName(u"label_autoriza_6")
        self.label_autoriza_6.setGeometry(QRect(20, 110, 171, 25))
        self.inputAltitud = QLineEdit(NewBook)
        self.inputAltitud.setObjectName(u"inputAltitud")
        self.inputAltitud.setGeometry(QRect(390, 135, 131, 31))
        self.inputAltitud.setFont(font1)
        self.inputAltitud.setMaxLength(4)
        self.label_autoriza_7 = QLabel(NewBook)
        self.label_autoriza_7.setObjectName(u"label_autoriza_7")
        self.label_autoriza_7.setGeometry(QRect(390, 110, 131, 25))
        self.label_autoriza_8 = QLabel(NewBook)
        self.label_autoriza_8.setObjectName(u"label_autoriza_8")
        self.label_autoriza_8.setGeometry(QRect(530, 110, 151, 25))
        self.cbCalificacion = QComboBox(NewBook)
        self.cbCalificacion.setObjectName(u"cbCalificacion")
        self.cbCalificacion.setGeometry(QRect(370, 75, 151, 31))
        self.cbCalificacion.setFont(font1)
        self.cbCalificacion.setEditable(False)
        self.inputModulo = QLineEdit(NewBook)
        self.inputModulo.setObjectName(u"inputModulo")
        self.inputModulo.setGeometry(QRect(400, 315, 121, 31))
        self.inputModulo.setFont(font1)
        self.inputModulo.setMaxLength(30)
        self.label_autoriza_23 = QLabel(NewBook)
        self.label_autoriza_23.setObjectName(u"label_autoriza_23")
        self.label_autoriza_23.setGeometry(QRect(400, 290, 121, 25))
        self.cbAreaOpe = QComboBox(NewBook)
        self.cbAreaOpe.setObjectName(u"cbAreaOpe")
        self.cbAreaOpe.setGeometry(QRect(940, 75, 201, 31))
        self.cbAreaOpe.setFont(font1)
        self.cbAreaOpe.setEditable(False)
        self.cbRegionGeografica = QComboBox(NewBook)
        self.cbRegionGeografica.setObjectName(u"cbRegionGeografica")
        self.cbRegionGeografica.setGeometry(QRect(20, 135, 191, 31))
        self.cbRegionGeografica.setFont(font1)
        self.cbRegionGeografica.setEditable(False)
        self.cbZona = QComboBox(NewBook)
        self.cbZona.setObjectName(u"cbZona")
        self.cbZona.setGeometry(QRect(220, 135, 161, 31))
        self.cbZona.setFont(font1)
        self.cbZona.setEditable(False)
        self.cbTipoRed = QComboBox(NewBook)
        self.cbTipoRed.setObjectName(u"cbTipoRed")
        self.cbTipoRed.setGeometry(QRect(530, 135, 191, 31))
        self.cbTipoRed.setFont(font1)
        self.cbTipoRed.setEditable(False)
        self.label_autoriza_9 = QLabel(NewBook)
        self.label_autoriza_9.setObjectName(u"label_autoriza_9")
        self.label_autoriza_9.setGeometry(QRect(730, 110, 151, 25))
        self.label_autoriza_10 = QLabel(NewBook)
        self.label_autoriza_10.setObjectName(u"label_autoriza_10")
        self.label_autoriza_10.setGeometry(QRect(940, 110, 151, 25))
        self.inputConductoresXFases = QLineEdit(NewBook)
        self.inputConductoresXFases.setObjectName(u"inputConductoresXFases")
        self.inputConductoresXFases.setGeometry(QRect(20, 195, 221, 31))
        self.inputConductoresXFases.setFont(font1)
        self.inputConductoresXFases.setMaxLength(1)
        self.label_autoriza_11 = QLabel(NewBook)
        self.label_autoriza_11.setObjectName(u"label_autoriza_11")
        self.label_autoriza_11.setGeometry(QRect(20, 170, 211, 25))
        self.label_autoriza_12 = QLabel(NewBook)
        self.label_autoriza_12.setObjectName(u"label_autoriza_12")
        self.label_autoriza_12.setGeometry(QRect(250, 170, 151, 25))
        self.cbTipoConductor = QComboBox(NewBook)
        self.cbTipoConductor.setObjectName(u"cbTipoConductor")
        self.cbTipoConductor.setGeometry(QRect(250, 195, 161, 31))
        self.cbTipoConductor.setFont(font1)
        self.cbTipoConductor.setEditable(False)
        self.label_autoriza_13 = QLabel(NewBook)
        self.label_autoriza_13.setObjectName(u"label_autoriza_13")
        self.label_autoriza_13.setGeometry(QRect(420, 170, 151, 25))
        self.inputSeccionConductor = QLineEdit(NewBook)
        self.inputSeccionConductor.setObjectName(u"inputSeccionConductor")
        self.inputSeccionConductor.setGeometry(QRect(420, 195, 231, 31))
        self.inputSeccionConductor.setFont(font1)
        self.inputSeccionConductor.setMaxLength(8)
        self.inputPotenciaN = QLineEdit(NewBook)
        self.inputPotenciaN.setObjectName(u"inputPotenciaN")
        self.inputPotenciaN.setGeometry(QRect(660, 195, 141, 31))
        self.inputPotenciaN.setFont(font1)
        self.inputPotenciaN.setMaxLength(8)
        self.label_autoriza_14 = QLabel(NewBook)
        self.label_autoriza_14.setObjectName(u"label_autoriza_14")
        self.label_autoriza_14.setGeometry(QRect(660, 170, 151, 25))
        self.label_autoriza_15 = QLabel(NewBook)
        self.label_autoriza_15.setObjectName(u"label_autoriza_15")
        self.label_autoriza_15.setGeometry(QRect(810, 170, 111, 25))
        self.inputCorrienteN = QLineEdit(NewBook)
        self.inputCorrienteN.setObjectName(u"inputCorrienteN")
        self.inputCorrienteN.setGeometry(QRect(810, 195, 161, 31))
        self.inputCorrienteN.setFont(font1)
        self.inputCorrienteN.setMaxLength(8)
        self.label_autoriza_16 = QLabel(NewBook)
        self.label_autoriza_16.setObjectName(u"label_autoriza_16")
        self.label_autoriza_16.setGeometry(QRect(20, 230, 111, 25))
        self.inputTensionN = QLineEdit(NewBook)
        self.inputTensionN.setObjectName(u"inputTensionN")
        self.inputTensionN.setGeometry(QRect(980, 195, 161, 31))
        self.inputTensionN.setFont(font1)
        self.inputTensionN.setMaxLength(8)
        self.inputTensionOpe = QLineEdit(NewBook)
        self.inputTensionOpe.setObjectName(u"inputTensionOpe")
        self.inputTensionOpe.setGeometry(QRect(20, 255, 141, 31))
        self.inputTensionOpe.setFont(font1)
        self.inputTensionOpe.setMaxLength(8)
        self.label_autoriza_17 = QLabel(NewBook)
        self.label_autoriza_17.setObjectName(u"label_autoriza_17")
        self.label_autoriza_17.setGeometry(QRect(980, 170, 151, 25))
        self.inputResistencia = QLineEdit(NewBook)
        self.inputResistencia.setObjectName(u"inputResistencia")
        self.inputResistencia.setGeometry(QRect(330, 255, 161, 31))
        self.inputResistencia.setFont(font1)
        self.inputResistencia.setMaxLength(9)
        self.label_autoriza_18 = QLabel(NewBook)
        self.label_autoriza_18.setObjectName(u"label_autoriza_18")
        self.label_autoriza_18.setGeometry(QRect(170, 230, 151, 25))
        self.label_autoriza_19 = QLabel(NewBook)
        self.label_autoriza_19.setObjectName(u"label_autoriza_19")
        self.label_autoriza_19.setGeometry(QRect(330, 230, 111, 25))
        self.inputTensionAisl = QLineEdit(NewBook)
        self.inputTensionAisl.setObjectName(u"inputTensionAisl")
        self.inputTensionAisl.setGeometry(QRect(170, 255, 151, 31))
        self.inputTensionAisl.setFont(font1)
        self.inputTensionAisl.setMaxLength(9)
        self.inputReactancia = QLineEdit(NewBook)
        self.inputReactancia.setObjectName(u"inputReactancia")
        self.inputReactancia.setGeometry(QRect(500, 255, 151, 31))
        self.inputReactancia.setFont(font1)
        self.inputReactancia.setMaxLength(9)
        self.label_autoriza_20 = QLabel(NewBook)
        self.label_autoriza_20.setObjectName(u"label_autoriza_20")
        self.label_autoriza_20.setGeometry(QRect(500, 230, 111, 25))
        self.inputSuceptancia = QLineEdit(NewBook)
        self.inputSuceptancia.setObjectName(u"inputSuceptancia")
        self.inputSuceptancia.setGeometry(QRect(660, 255, 141, 31))
        self.inputSuceptancia.setFont(font1)
        self.inputSuceptancia.setMaxLength(9)
        self.label_autoriza_21 = QLabel(NewBook)
        self.label_autoriza_21.setObjectName(u"label_autoriza_21")
        self.label_autoriza_21.setGeometry(QRect(660, 230, 111, 25))
        self.label_autoriza_22 = QLabel(NewBook)
        self.label_autoriza_22.setObjectName(u"label_autoriza_22")
        self.label_autoriza_22.setGeometry(QRect(810, 230, 121, 25))
        self.inputConductancia = QLineEdit(NewBook)
        self.inputConductancia.setObjectName(u"inputConductancia")
        self.inputConductancia.setGeometry(QRect(810, 255, 161, 31))
        self.inputConductancia.setFont(font1)
        self.inputConductancia.setMaxLength(9)
        self.label_autoriza_24 = QLabel(NewBook)
        self.label_autoriza_24.setObjectName(u"label_autoriza_24")
        self.label_autoriza_24.setGeometry(QRect(980, 230, 161, 25))
        self.cbMatCable = QComboBox(NewBook)
        self.cbMatCable.setObjectName(u"cbMatCable")
        self.cbMatCable.setGeometry(QRect(20, 315, 211, 31))
        self.cbMatCable.setFont(font1)
        self.cbMatCable.setEditable(False)
        self.label_autoriza_25 = QLabel(NewBook)
        self.label_autoriza_25.setObjectName(u"label_autoriza_25")
        self.label_autoriza_25.setGeometry(QRect(20, 290, 151, 25))
        self.inputSeccionCableG = QLineEdit(NewBook)
        self.inputSeccionCableG.setObjectName(u"inputSeccionCableG")
        self.inputSeccionCableG.setGeometry(QRect(240, 315, 151, 31))
        self.inputSeccionCableG.setFont(font1)
        self.inputSeccionCableG.setMaxLength(8)
        self.label_autoriza_26 = QLabel(NewBook)
        self.label_autoriza_26.setObjectName(u"label_autoriza_26")
        self.label_autoriza_26.setGeometry(QRect(240, 290, 151, 25))
        self.label_autoriza_27 = QLabel(NewBook)
        self.label_autoriza_27.setObjectName(u"label_autoriza_27")
        self.label_autoriza_27.setGeometry(QRect(780, 290, 121, 25))
        self.inputDatum = QLineEdit(NewBook)
        self.inputDatum.setObjectName(u"inputDatum")
        self.inputDatum.setGeometry(QRect(780, 315, 121, 31))
        self.inputDatum.setFont(font1)
        self.inputDatum.setMaxLength(10)
        self.inputZonaUTM = QLineEdit(NewBook)
        self.inputZonaUTM.setObjectName(u"inputZonaUTM")
        self.inputZonaUTM.setGeometry(QRect(910, 315, 101, 31))
        self.inputZonaUTM.setFont(font1)
        self.inputZonaUTM.setMaxLength(5)
        self.label_autoriza_28 = QLabel(NewBook)
        self.label_autoriza_28.setObjectName(u"label_autoriza_28")
        self.label_autoriza_28.setGeometry(QRect(910, 290, 101, 25))
        self.cbNCablesGuarda = QComboBox(NewBook)
        self.cbNCablesGuarda.setObjectName(u"cbNCablesGuarda")
        self.cbNCablesGuarda.setGeometry(QRect(980, 255, 161, 31))
        self.cbNCablesGuarda.setFont(font1)
        self.cbNCablesGuarda.setEditable(False)
        self.cbDispFases = QComboBox(NewBook)
        self.cbDispFases.setObjectName(u"cbDispFases")
        self.cbDispFases.setGeometry(QRect(940, 135, 201, 31))
        self.cbDispFases.setFont(font1)
        self.cbDispFases.setEditable(False)
        self.cbAreaDemanda = QComboBox(NewBook)
        self.cbAreaDemanda.setObjectName(u"cbAreaDemanda")
        self.cbAreaDemanda.setGeometry(QRect(730, 75, 201, 31))
        self.cbAreaDemanda.setFont(font1)
        self.cbAreaDemanda.setEditable(False)
        self.tableInterruptores = QTableWidget(NewBook)
        self.tableInterruptores.setObjectName(u"tableInterruptores")
        self.tableInterruptores.setGeometry(QRect(380, 390, 411, 181))
        self.tableInterruptores.setAutoFillBackground(True)
        self.tableInterruptores.setLineWidth(5)
        self.tableInterruptores.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableInterruptores.setTextElideMode(Qt.ElideLeft)
        self.tableInterruptores.horizontalHeader().setMinimumSectionSize(10)
        self.label_4 = QLabel(NewBook)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(380, 370, 321, 21))
        self.btnAddInterruptor = QPushButton(NewBook)
        self.btnAddInterruptor.setObjectName(u"btnAddInterruptor")
        self.btnAddInterruptor.setGeometry(QRect(720, 360, 31, 31))
        font4 = QFont()
        font4.setPointSize(12)
        font4.setBold(True)
        font4.setWeight(75)
        self.btnAddInterruptor.setFont(font4)
        self.btnAddInterruptor.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnAddInterruptor.setStyleSheet(u"QPushButton\n"
"{	\n"
"	height: 2em;\n"
" 	border-style: solid;\n"
"	border-width: 2px;\n"
" 	border-color: #0069c0;\n"
"	font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	background-color:#0069c0;\n"
"	color:white;\n"
"}")
        self.btnAddInterruptor.setIcon(icon)
        self.btnAddInterruptor.setIconSize(QSize(30, 30))
        self.btnAddInterruptor.setAutoDefault(True)
        self.btnAddInterruptor.setFlat(True)
        self.btnDeleteInterruptor = QPushButton(NewBook)
        self.btnDeleteInterruptor.setObjectName(u"btnDeleteInterruptor")
        self.btnDeleteInterruptor.setGeometry(QRect(760, 360, 31, 31))
        self.btnDeleteInterruptor.setFont(font4)
        self.btnDeleteInterruptor.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnDeleteInterruptor.setStyleSheet(u"QPushButton\n"
"{	\n"
"	height: 2em;\n"
" 	border-style: solid;\n"
"	border-width: 2px;\n"
" 	border-color: #0069c0;\n"
"	font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	background-color:#0069c0;\n"
"	color:white;\n"
"}")
        icon2 = QIcon()
        icon2.addFile(u"./assets/icons/db_negative.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnDeleteInterruptor.setIcon(icon2)
        self.btnDeleteInterruptor.setIconSize(QSize(30, 30))
        self.btnDeleteInterruptor.setAutoDefault(True)
        self.btnDeleteInterruptor.setFlat(True)
        self.label_empresa = QLabel(NewBook)
        self.label_empresa.setObjectName(u"label_empresa")
        self.label_empresa.setGeometry(QRect(1020, 290, 111, 21))
        self.label_empresa.setScaledContents(True)
        self.inputCodEmpresa = QLineEdit(NewBook)
        self.inputCodEmpresa.setObjectName(u"inputCodEmpresa")
        self.inputCodEmpresa.setGeometry(QRect(1020, 315, 121, 31))
        self.inputCodEmpresa.setFont(font1)
        self.inputCodEmpresa.setMaxLength(5)
        QWidget.setTabOrder(self.inputCodigo, self.inputCentral)
        QWidget.setTabOrder(self.inputCentral, self.addButton)
        QWidget.setTabOrder(self.addButton, self.cancelButton)

        self.retranslateUi(NewBook)

        self.addButton.setDefault(True)
        self.cancelButton.setDefault(True)
        self.btnAddInterruptor.setDefault(True)
        self.btnDeleteInterruptor.setDefault(True)


        QMetaObject.connectSlotsByName(NewBook)
    # setupUi

    def retranslateUi(self, NewBook):
        NewBook.setWindowTitle(QCoreApplication.translate("NewBook", u"Nuevo Registro", None))
        self.label.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">TRAMO DE L\u00cdNEA DE TRANSMISI\u00d3N</span></p></body></html>", None))
        self.label_autoriza.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Codigo:</span></p></body></html>", None))
        self.addButton.setText(QCoreApplication.translate("NewBook", u"AGREGAR", None))
        self.cancelButton.setText(QCoreApplication.translate("NewBook", u"CANCELAR", None))
        self.label_aquienVisita.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">L\u00ednea de Transmisi\u00f3n:</span></p></body></html>", None))
        self.label_area.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">\u00c1rea Demanda:</span></p></body></html>", None))
        self.label_horaSalida.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Estado:</span></p></body></html>", None))
        self.label_motivoVisita.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Fecha de Alta:</span></p></body></html>", None))
        self.label_nota_obligatoria.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic; color:#ff0000;\">(*) El c\u00f3digo es obligatorio</span></p></body></html>", None))
        self.ast_aquienvisita.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">*</span></p></body></html>", None))
        self.label_advertencia_dni.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic; color:#ff0000;\">(*) El c\u00f3digo es obligatorio</span></p></body></html>", None))
        self.label_area_2.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Calificaci\u00f3n:</span></p></body></html>", None))
        self.label_area_3.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tipo:</span></p></body></html>", None))
        self.label_autoriza_4.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Zona:</span></p></body></html>", None))
        self.label_autoriza_5.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">\u00c1rea Operativa:</span></p></body></html>", None))
        self.label_autoriza_6.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Regi\u00f3n Geografica:</span></p></body></html>", None))
        self.label_autoriza_7.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Altitud:</span></p></body></html>", None))
        self.label_autoriza_8.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tipo Red:</span></p></body></html>", None))
        self.label_autoriza_23.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">M\u00f3dulo:</span></p></body></html>", None))
        self.label_autoriza_9.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Longitud:</span></p></body></html>", None))
        self.label_autoriza_10.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Disp. Fases:</span></p></body></html>", None))
        self.label_autoriza_11.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">N\u00b0 Conductores x Fases:</span></p></body></html>", None))
        self.label_autoriza_12.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tipo Conductor:</span></p></body></html>", None))
        self.label_autoriza_13.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Secci\u00f3n Conductor:</span></p></body></html>", None))
        self.label_autoriza_14.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Potencia N.:</span></p></body></html>", None))
        self.label_autoriza_15.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Corriente N.:</span></p></body></html>", None))
        self.label_autoriza_16.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tensi\u00f3n Op.:</span></p></body></html>", None))
        self.label_autoriza_17.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tensi\u00f3n N.:</span></p></body></html>", None))
        self.label_autoriza_18.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tensi\u00f3n Aisl.:</span></p></body></html>", None))
        self.label_autoriza_19.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Resistencia:</span></p></body></html>", None))
        self.label_autoriza_20.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Reactancia:</span></p></body></html>", None))
        self.label_autoriza_21.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Suceptancia:</span></p></body></html>", None))
        self.label_autoriza_22.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Conductancia:</span></p></body></html>", None))
        self.label_autoriza_24.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">N\u00b0 Cables Guarda:</span></p></body></html>", None))
        self.label_autoriza_25.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Mat. Cable Guarda:</span></p></body></html>", None))
        self.label_autoriza_26.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Secci\u00f3n Cable Guarda:</span></p></body></html>", None))
        self.label_autoriza_27.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Datum:</span></p></body></html>", None))
        self.label_autoriza_28.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Zona UTM:</span></p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Vertices de Ubicaci\u00f3n Geogr\u00e1fica:</span></p></body></html>", None))
        self.btnAddInterruptor.setText("")
        self.btnDeleteInterruptor.setText("")
        self.label_empresa.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Empresa:</span></p></body></html>", None))
    # retranslateUi

