# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'new_transmision_linea_Estructura.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_NewBook(object):
    def setupUi(self, NewBook):
        if not NewBook.objectName():
            NewBook.setObjectName(u"NewBook")
        NewBook.resize(1019, 440)
        NewBook.setMinimumSize(QSize(1019, 440))
        NewBook.setMaximumSize(QSize(1019, 440))
        NewBook.setStyleSheet(u"QPushButton\n"
"{	\n"
"	height: 2em;\n"
" 	border-style: solid;\n"
"	border-width: 2px;\n"
" 	border-color: grey;\n"
"	font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	background-color:grey;\n"
"	color:white;\n"
"}")
        self.label = QLabel(NewBook)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 991, 41))
        font = QFont()
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet(u"background-color: red;")
        self.label.setFrameShape(QFrame.Box)
        self.label_autoriza = QLabel(NewBook)
        self.label_autoriza.setObjectName(u"label_autoriza")
        self.label_autoriza.setGeometry(QRect(20, 70, 101, 25))
        self.inputCodigo = QLineEdit(NewBook)
        self.inputCodigo.setObjectName(u"inputCodigo")
        self.inputCodigo.setGeometry(QRect(20, 95, 121, 31))
        font1 = QFont()
        font1.setPointSize(12)
        self.inputCodigo.setFont(font1)
        self.inputCodigo.setMaxLength(12)
        self.inputLineaTransmision = QLineEdit(NewBook)
        self.inputLineaTransmision.setObjectName(u"inputLineaTransmision")
        self.inputLineaTransmision.setGeometry(QRect(150, 95, 221, 31))
        self.inputLineaTransmision.setFont(font1)
        self.addButton = QPushButton(NewBook)
        self.addButton.setObjectName(u"addButton")
        self.addButton.setGeometry(QRect(200, 380, 291, 41))
        font2 = QFont()
        font2.setPointSize(14)
        font2.setBold(True)
        font2.setWeight(75)
        self.addButton.setFont(font2)
        self.addButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.addButton.setStyleSheet(u"QPushButton\n"
"{	\n"
"	height: 2em;\n"
" 	border-style: solid;\n"
"	border-width: 2px;\n"
" 	border-color: #0069c0;\n"
"	font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	background-color:#0069c0;\n"
"	color:white;\n"
"}")
        icon = QIcon()
        icon.addFile(u"./assets/icons/add-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.addButton.setIcon(icon)
        self.addButton.setIconSize(QSize(30, 30))
        self.addButton.setAutoDefault(True)
        self.addButton.setFlat(True)
        self.cancelButton = QPushButton(NewBook)
        self.cancelButton.setObjectName(u"cancelButton")
        self.cancelButton.setGeometry(QRect(530, 380, 271, 41))
        self.cancelButton.setFont(font2)
        self.cancelButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.cancelButton.setStyleSheet(u"QPushButton\n"
"{	\n"
"	height: 2em;\n"
" 	border-style: solid;\n"
"	border-width: 2px;\n"
" 	border-color: grey;\n"
"	font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	background-color:grey;\n"
"	color:white;\n"
"}")
        icon1 = QIcon()
        icon1.addFile(u"./assets/icons/cancel-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.cancelButton.setIcon(icon1)
        self.cancelButton.setIconSize(QSize(30, 30))
        self.cancelButton.setAutoDefault(True)
        self.cancelButton.setFlat(True)
        self.label_aquienVisita = QLabel(NewBook)
        self.label_aquienVisita.setObjectName(u"label_aquienVisita")
        self.label_aquienVisita.setGeometry(QRect(150, 70, 191, 25))
        self.label_horaSalida = QLabel(NewBook)
        self.label_horaSalida.setObjectName(u"label_horaSalida")
        self.label_horaSalida.setGeometry(QRect(640, 130, 81, 25))
        self.label_motivoVisita = QLabel(NewBook)
        self.label_motivoVisita.setObjectName(u"label_motivoVisita")
        self.label_motivoVisita.setGeometry(QRect(770, 130, 111, 25))
        self.label_nota_obligatoria = QLabel(NewBook)
        self.label_nota_obligatoria.setObjectName(u"label_nota_obligatoria")
        self.label_nota_obligatoria.setGeometry(QRect(20, 360, 281, 21))
        self.label_advertencia_dni = QLabel(NewBook)
        self.label_advertencia_dni.setObjectName(u"label_advertencia_dni")
        self.label_advertencia_dni.setGeometry(QRect(20, 360, 251, 21))
        self.cbEstado = QComboBox(NewBook)
        self.cbEstado.setObjectName(u"cbEstado")
        self.cbEstado.setGeometry(QRect(640, 155, 121, 31))
        self.cbEstado.setFont(font1)
        self.cbEstado.setEditable(False)
        self.inputFecha = QDateEdit(NewBook)
        self.inputFecha.setObjectName(u"inputFecha")
        self.inputFecha.setGeometry(QRect(770, 155, 111, 31))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(False)
        font3.setWeight(50)
        self.inputFecha.setFont(font3)
        self.cbTipo = QComboBox(NewBook)
        self.cbTipo.setObjectName(u"cbTipo")
        self.cbTipo.setGeometry(QRect(380, 95, 191, 31))
        self.cbTipo.setFont(font1)
        self.cbTipo.setEditable(False)
        self.label_area_3 = QLabel(NewBook)
        self.label_area_3.setObjectName(u"label_area_3")
        self.label_area_3.setGeometry(QRect(380, 70, 141, 25))
        self.cbCalificacion = QComboBox(NewBook)
        self.cbCalificacion.setObjectName(u"cbCalificacion")
        self.cbCalificacion.setGeometry(QRect(580, 95, 191, 31))
        self.cbCalificacion.setFont(font1)
        self.cbCalificacion.setEditable(False)
        self.label_area_4 = QLabel(NewBook)
        self.label_area_4.setObjectName(u"label_area_4")
        self.label_area_4.setGeometry(QRect(580, 70, 141, 25))
        self.cbFuncion = QComboBox(NewBook)
        self.cbFuncion.setObjectName(u"cbFuncion")
        self.cbFuncion.setGeometry(QRect(780, 95, 231, 31))
        self.cbFuncion.setFont(font1)
        self.cbFuncion.setEditable(False)
        self.label_area_5 = QLabel(NewBook)
        self.label_area_5.setObjectName(u"label_area_5")
        self.label_area_5.setGeometry(QRect(780, 70, 141, 25))
        self.label_autoriza_2 = QLabel(NewBook)
        self.label_autoriza_2.setObjectName(u"label_autoriza_2")
        self.label_autoriza_2.setGeometry(QRect(20, 130, 101, 25))
        self.inputAltura = QLineEdit(NewBook)
        self.inputAltura.setObjectName(u"inputAltura")
        self.inputAltura.setGeometry(QRect(20, 155, 81, 31))
        self.inputAltura.setFont(font1)
        self.inputAltura.setMaxLength(7)
        self.label_autoriza_3 = QLabel(NewBook)
        self.label_autoriza_3.setObjectName(u"label_autoriza_3")
        self.label_autoriza_3.setGeometry(QRect(110, 130, 101, 25))
        self.cbNCircuitos = QComboBox(NewBook)
        self.cbNCircuitos.setObjectName(u"cbNCircuitos")
        self.cbNCircuitos.setGeometry(QRect(110, 155, 91, 31))
        self.cbNCircuitos.setFont(font1)
        self.cbNCircuitos.setEditable(False)
        self.cbFormacion = QComboBox(NewBook)
        self.cbFormacion.setObjectName(u"cbFormacion")
        self.cbFormacion.setGeometry(QRect(210, 155, 121, 31))
        self.cbFormacion.setFont(font1)
        self.cbFormacion.setEditable(False)
        self.label_autoriza_4 = QLabel(NewBook)
        self.label_autoriza_4.setObjectName(u"label_autoriza_4")
        self.label_autoriza_4.setGeometry(QRect(210, 130, 101, 25))
        self.label_autoriza_5 = QLabel(NewBook)
        self.label_autoriza_5.setObjectName(u"label_autoriza_5")
        self.label_autoriza_5.setGeometry(QRect(340, 130, 121, 25))
        self.inputLocalidad = QLineEdit(NewBook)
        self.inputLocalidad.setObjectName(u"inputLocalidad")
        self.inputLocalidad.setGeometry(QRect(470, 155, 161, 31))
        self.inputLocalidad.setFont(font1)
        self.inputLocalidad.setMaxLength(50)
        self.label_autoriza_6 = QLabel(NewBook)
        self.label_autoriza_6.setObjectName(u"label_autoriza_6")
        self.label_autoriza_6.setGeometry(QRect(470, 130, 161, 25))
        self.groupBox = QGroupBox(NewBook)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 200, 321, 161))
        font4 = QFont()
        font4.setPointSize(11)
        font4.setBold(True)
        font4.setWeight(75)
        self.groupBox.setFont(font4)
        self.groupBox.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_motivoVisita_2 = QLabel(self.groupBox)
        self.label_motivoVisita_2.setObjectName(u"label_motivoVisita_2")
        self.label_motivoVisita_2.setGeometry(QRect(100, 90, 61, 25))
        self.inputDatum = QLineEdit(self.groupBox)
        self.inputDatum.setObjectName(u"inputDatum")
        self.inputDatum.setGeometry(QRect(10, 55, 101, 31))
        self.inputDatum.setFont(font1)
        self.inputDatum.setMaxLength(10)
        self.inputX = QLineEdit(self.groupBox)
        self.inputX.setObjectName(u"inputX")
        self.inputX.setGeometry(QRect(220, 55, 81, 31))
        self.inputX.setFont(font1)
        self.inputX.setMaxLength(14)
        self.inputY = QLineEdit(self.groupBox)
        self.inputY.setObjectName(u"inputY")
        self.inputY.setGeometry(QRect(10, 115, 81, 31))
        self.inputY.setFont(font1)
        self.inputY.setMaxLength(14)
        self.inputZona = QLineEdit(self.groupBox)
        self.inputZona.setObjectName(u"inputZona")
        self.inputZona.setGeometry(QRect(120, 55, 91, 31))
        self.inputZona.setFont(font1)
        self.inputZona.setMaxLength(5)
        self.inputANG = QLineEdit(self.groupBox)
        self.inputANG.setObjectName(u"inputANG")
        self.inputANG.setGeometry(QRect(190, 115, 111, 31))
        self.inputANG.setFont(font1)
        self.inputANG.setMaxLength(11)
        self.label_horaSalida_2 = QLabel(self.groupBox)
        self.label_horaSalida_2.setObjectName(u"label_horaSalida_2")
        self.label_horaSalida_2.setGeometry(QRect(10, 90, 81, 25))
        self.label_horaIngreso = QLabel(self.groupBox)
        self.label_horaIngreso.setObjectName(u"label_horaIngreso")
        self.label_horaIngreso.setGeometry(QRect(220, 30, 71, 25))
        self.label_motivoVisita_3 = QLabel(self.groupBox)
        self.label_motivoVisita_3.setObjectName(u"label_motivoVisita_3")
        self.label_motivoVisita_3.setGeometry(QRect(10, 30, 101, 25))
        self.label_motivoVisita_5 = QLabel(self.groupBox)
        self.label_motivoVisita_5.setObjectName(u"label_motivoVisita_5")
        self.label_motivoVisita_5.setGeometry(QRect(190, 90, 101, 25))
        self.inputZ = QLineEdit(self.groupBox)
        self.inputZ.setObjectName(u"inputZ")
        self.inputZ.setGeometry(QRect(100, 115, 81, 31))
        self.inputZ.setFont(font1)
        self.inputZ.setMaxLength(14)
        self.label_motivoVisita_4 = QLabel(self.groupBox)
        self.label_motivoVisita_4.setObjectName(u"label_motivoVisita_4")
        self.label_motivoVisita_4.setGeometry(QRect(120, 30, 91, 25))
        self.groupBox_2 = QGroupBox(NewBook)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(350, 200, 321, 161))
        self.groupBox_2.setFont(font4)
        self.groupBox_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_motivoVisita_6 = QLabel(self.groupBox_2)
        self.label_motivoVisita_6.setObjectName(u"label_motivoVisita_6")
        self.label_motivoVisita_6.setGeometry(QRect(100, 90, 61, 25))
        self.inputSubestacion = QLineEdit(self.groupBox_2)
        self.inputSubestacion.setObjectName(u"inputSubestacion")
        self.inputSubestacion.setGeometry(QRect(10, 55, 141, 31))
        self.inputSubestacion.setFont(font1)
        self.inputSubestacion.setMaxLength(20)
        self.inputX_2 = QLineEdit(self.groupBox_2)
        self.inputX_2.setObjectName(u"inputX_2")
        self.inputX_2.setGeometry(QRect(160, 55, 81, 31))
        self.inputX_2.setFont(font1)
        self.inputX_2.setMaxLength(14)
        self.inputY_2 = QLineEdit(self.groupBox_2)
        self.inputY_2.setObjectName(u"inputY_2")
        self.inputY_2.setGeometry(QRect(10, 115, 81, 31))
        self.inputY_2.setFont(font1)
        self.inputY_2.setMaxLength(14)
        self.inputANG_2 = QLineEdit(self.groupBox_2)
        self.inputANG_2.setObjectName(u"inputANG_2")
        self.inputANG_2.setGeometry(QRect(190, 115, 111, 31))
        self.inputANG_2.setFont(font1)
        self.inputANG_2.setMaxLength(11)
        self.label_horaSalida_3 = QLabel(self.groupBox_2)
        self.label_horaSalida_3.setObjectName(u"label_horaSalida_3")
        self.label_horaSalida_3.setGeometry(QRect(10, 90, 81, 25))
        self.label_horaIngreso_2 = QLabel(self.groupBox_2)
        self.label_horaIngreso_2.setObjectName(u"label_horaIngreso_2")
        self.label_horaIngreso_2.setGeometry(QRect(160, 30, 71, 25))
        self.label_motivoVisita_7 = QLabel(self.groupBox_2)
        self.label_motivoVisita_7.setObjectName(u"label_motivoVisita_7")
        self.label_motivoVisita_7.setGeometry(QRect(10, 30, 141, 25))
        self.label_motivoVisita_8 = QLabel(self.groupBox_2)
        self.label_motivoVisita_8.setObjectName(u"label_motivoVisita_8")
        self.label_motivoVisita_8.setGeometry(QRect(190, 90, 101, 25))
        self.inputZ_2 = QLineEdit(self.groupBox_2)
        self.inputZ_2.setObjectName(u"inputZ_2")
        self.inputZ_2.setGeometry(QRect(100, 115, 81, 31))
        self.inputZ_2.setFont(font1)
        self.inputZ_2.setMaxLength(14)
        self.groupBox_3 = QGroupBox(NewBook)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(680, 200, 331, 161))
        self.groupBox_3.setFont(font4)
        self.groupBox_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_motivoVisita_9 = QLabel(self.groupBox_3)
        self.label_motivoVisita_9.setObjectName(u"label_motivoVisita_9")
        self.label_motivoVisita_9.setGeometry(QRect(100, 90, 61, 25))
        self.inputCentral = QLineEdit(self.groupBox_3)
        self.inputCentral.setObjectName(u"inputCentral")
        self.inputCentral.setGeometry(QRect(10, 55, 141, 31))
        self.inputCentral.setFont(font1)
        self.inputCentral.setMaxLength(20)
        self.inputX_3 = QLineEdit(self.groupBox_3)
        self.inputX_3.setObjectName(u"inputX_3")
        self.inputX_3.setGeometry(QRect(160, 55, 81, 31))
        self.inputX_3.setFont(font1)
        self.inputX_3.setMaxLength(14)
        self.inputY_3 = QLineEdit(self.groupBox_3)
        self.inputY_3.setObjectName(u"inputY_3")
        self.inputY_3.setGeometry(QRect(10, 115, 81, 31))
        self.inputY_3.setFont(font1)
        self.inputY_3.setMaxLength(14)
        self.inputANG_3 = QLineEdit(self.groupBox_3)
        self.inputANG_3.setObjectName(u"inputANG_3")
        self.inputANG_3.setGeometry(QRect(190, 115, 111, 31))
        self.inputANG_3.setFont(font1)
        self.inputANG_3.setMaxLength(11)
        self.label_horaSalida_4 = QLabel(self.groupBox_3)
        self.label_horaSalida_4.setObjectName(u"label_horaSalida_4")
        self.label_horaSalida_4.setGeometry(QRect(10, 90, 81, 25))
        self.label_horaIngreso_3 = QLabel(self.groupBox_3)
        self.label_horaIngreso_3.setObjectName(u"label_horaIngreso_3")
        self.label_horaIngreso_3.setGeometry(QRect(160, 30, 71, 25))
        self.label_motivoVisita_10 = QLabel(self.groupBox_3)
        self.label_motivoVisita_10.setObjectName(u"label_motivoVisita_10")
        self.label_motivoVisita_10.setGeometry(QRect(10, 30, 131, 25))
        self.label_motivoVisita_11 = QLabel(self.groupBox_3)
        self.label_motivoVisita_11.setObjectName(u"label_motivoVisita_11")
        self.label_motivoVisita_11.setGeometry(QRect(190, 90, 101, 25))
        self.inputZ_3 = QLineEdit(self.groupBox_3)
        self.inputZ_3.setObjectName(u"inputZ_3")
        self.inputZ_3.setGeometry(QRect(100, 115, 81, 31))
        self.inputZ_3.setFont(font1)
        self.inputZ_3.setMaxLength(14)
        self.label_advertencia_dni_2 = QLabel(NewBook)
        self.label_advertencia_dni_2.setObjectName(u"label_advertencia_dni_2")
        self.label_advertencia_dni_2.setGeometry(QRect(70, 70, 31, 21))
        self.cbNCables = QComboBox(NewBook)
        self.cbNCables.setObjectName(u"cbNCables")
        self.cbNCables.setGeometry(QRect(340, 155, 121, 31))
        self.cbNCables.setFont(font1)
        self.cbNCables.setEditable(False)
        self.label_empresa = QLabel(NewBook)
        self.label_empresa.setObjectName(u"label_empresa")
        self.label_empresa.setGeometry(QRect(890, 130, 111, 21))
        self.label_empresa.setScaledContents(True)
        self.inputCodEmpresa = QLineEdit(NewBook)
        self.inputCodEmpresa.setObjectName(u"inputCodEmpresa")
        self.inputCodEmpresa.setGeometry(QRect(890, 155, 121, 31))
        self.inputCodEmpresa.setFont(font1)
        self.inputCodEmpresa.setMaxLength(5)
        QWidget.setTabOrder(self.inputCodigo, self.inputLineaTransmision)
        QWidget.setTabOrder(self.inputLineaTransmision, self.addButton)
        QWidget.setTabOrder(self.addButton, self.cancelButton)

        self.retranslateUi(NewBook)

        self.addButton.setDefault(True)
        self.cancelButton.setDefault(True)


        QMetaObject.connectSlotsByName(NewBook)
    # setupUi

    def retranslateUi(self, NewBook):
        NewBook.setWindowTitle(QCoreApplication.translate("NewBook", u"Nuevo Registro", None))
        self.label.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">ESTRUCTURA</span></p></body></html>", None))
        self.label_autoriza.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Codigo:</span></p></body></html>", None))
        self.addButton.setText(QCoreApplication.translate("NewBook", u"AGREGAR", None))
        self.cancelButton.setText(QCoreApplication.translate("NewBook", u"CANCELAR", None))
        self.label_aquienVisita.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">L\u00ednea de Transmisi\u00f3n:</span></p></body></html>", None))
        self.label_horaSalida.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Estado:</span></p></body></html>", None))
        self.label_motivoVisita.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Fecha de Alta:</span></p></body></html>", None))
        self.label_nota_obligatoria.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic; color:#ff0000;\">(*) El c\u00f3digo es obligatorio</span></p></body></html>", None))
        self.label_advertencia_dni.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic; color:#ff0000;\">(*) El c\u00f3digo es obligatorio</span></p></body></html>", None))
        self.label_area_3.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tipo:</span></p></body></html>", None))
        self.label_area_4.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Calificaci\u00f3n:</span></p></body></html>", None))
        self.label_area_5.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Funci\u00f3n:</span></p></body></html>", None))
        self.label_autoriza_2.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Altura:</span></p></body></html>", None))
        self.label_autoriza_3.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">N\u00b0 Circuitos:</span></p></body></html>", None))
        self.label_autoriza_4.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Formaci\u00f3n:</span></p></body></html>", None))
        self.label_autoriza_5.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">N\u00b0 Cables Guarda:</span></p></body></html>", None))
        self.label_autoriza_6.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Localidad:</span></p></body></html>", None))
        self.groupBox.setTitle(QCoreApplication.translate("NewBook", u"V\u00e9rtice de Ubicaci\u00f3n Geogr\u00e1fica", None))
        self.label_motivoVisita_2.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Z:</span></p></body></html>", None))
        self.label_horaSalida_2.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Y:</span></p></body></html>", None))
        self.label_horaIngreso.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">X:</span></p></body></html>", None))
        self.label_motivoVisita_3.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Datum:</span></p></body></html>", None))
        self.label_motivoVisita_5.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">ANG:</span></p></body></html>", None))
        self.label_motivoVisita_4.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Zona:</span></p></body></html>", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("NewBook", u"Ubicaci\u00f3n Plano Planta Subestaci\u00f3n", None))
        self.label_motivoVisita_6.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Z:</span></p></body></html>", None))
        self.label_horaSalida_3.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Y:</span></p></body></html>", None))
        self.label_horaIngreso_2.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">X:</span></p></body></html>", None))
        self.label_motivoVisita_7.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Subestaci\u00f3n:</span></p></body></html>", None))
        self.label_motivoVisita_8.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">ANG:</span></p></body></html>", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("NewBook", u"Ubicaci\u00f3n Plano Planta Central Gen.", None))
        self.label_motivoVisita_9.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Z:</span></p></body></html>", None))
        self.label_horaSalida_4.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Y:</span></p></body></html>", None))
        self.label_horaIngreso_3.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">X:</span></p></body></html>", None))
        self.label_motivoVisita_10.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Central:</span></p></body></html>", None))
        self.label_motivoVisita_11.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">ANG:</span></p></body></html>", None))
        self.label_advertencia_dni_2.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic; color:#ff0000;\">*</span></p></body></html>", None))
        self.label_empresa.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Empresa:</span></p></body></html>", None))
    # retranslateUi

